version: '3'

services:
  db:
    image: postgres
    container_name: db_postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

#  Django
  web:
    hostname: django
    container_name: django
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always